name: Node.js CI/CD Pipeline

on:
  push:
    branches: [main, develop, features/**, hotfix/**]

jobs:
  conventional-commits-check:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/heads/features/') || startsWith(github.ref, 'refs/heads/hotfix/')
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Validate Conventional Commits
        uses: webiny/action-conventional-commits@v1.1.0
        with:
          commitTypes: |
            feat
            fix
            docs
            style
            refactor
            perf
            test
            build
            ci
            chore
            revert
          commitScopes: ""
          github-token: ${{ secrets.GITHUB_TOKEN }}

  build:
    runs-on: ubuntu-latest
    needs: [conventional-commits-check]
    if: always()

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run tests
      run: npm test
      
    - name: Build
      run: npm run build --if-present

  # Protection des branches main et develop
  protect-branches:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Branch Protection Check
      run: |
        if [[ ("${{ github.ref }}" == "refs/heads/main" || "${{ github.ref }}" == "refs/heads/develop") && "${{ github.event_name }}" == "push" ]]; then
          echo "Les push directs sur les branches main et develop ne sont pas autorisés. Veuillez utiliser une Pull Request."
          exit 1
        fi