name: Suppression Automatique des Branches

on:
  pull_request:
    types: [closed]
    branches:
      - develop
      - main

jobs:
  delete-merged-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Extraire les informations de la branche
        id: branch-info
        run: |
          HEAD_REF="${{ github.head_ref }}"
          BASE_REF="${{ github.base_ref }}"
          
          # Vérifier si c'est une branche feature vers develop ou hotfix vers main
          if [[ "$HEAD_REF" =~ ^feature/ && "$BASE_REF" == "develop" ]]; then
            echo "can_delete=true" >> $GITHUB_OUTPUT
            echo "branch_type=feature" >> $GITHUB_OUTPUT
          elif [[ "$HEAD_REF" =~ ^hotfix/ && "$BASE_REF" == "main" ]]; then
            echo "can_delete=true" >> $GITHUB_OUTPUT
            echo "branch_type=hotfix" >> $GITHUB_OUTPUT
          else
            echo "can_delete=false" >> $GITHUB_OUTPUT
            echo "branch_type=other" >> $GITHUB_OUTPUT
          fi
          
          echo "branch_name=$HEAD_REF" >> $GITHUB_OUTPUT

      - name: Vérifications de sécurité
        id: security-check
        if: steps.branch-info.outputs.can_delete == 'true' && github.event.pull_request.merged == true
        run: |
          # Liste de branches protégées
          PROTECTED_BRANCHES=("main" "develop" "master" "production" "staging")
          
          BRANCH="${{ steps.branch-info.outputs.branch_name }}"
          
          # Vérifier si la branche est dans la liste des branches protégées
          for protected in "${PROTECTED_BRANCHES[@]}"; do
            if [[ "$BRANCH" == "$protected" ]]; then
              echo "❌ ERREUR: Tentative de suppression d'une branche protégée ($BRANCH)"
              echo "is_safe=false" >> $GITHUB_OUTPUT
              exit 0
            fi
          done
          
          # Vérifier le format de la branche
          if [[ "${{ steps.branch-info.outputs.branch_type }}" == "feature" && ! "$BRANCH" =~ ^feature/ ]]; then
            echo "❌ ERREUR: Format de branche feature invalide"
            echo "is_safe=false" >> $GITHUB_OUTPUT
            exit 0
          elif [[ "${{ steps.branch-info.outputs.branch_type }}" == "hotfix" && ! "$BRANCH" =~ ^hotfix/ ]]; then
            echo "❌ ERREUR: Format de branche hotfix invalide"
            echo "is_safe=false" >> $GITHUB_OUTPUT
            exit 0
          fi
          
          echo "is_safe=true" >> $GITHUB_OUTPUT

      - name: Supprimer la branche
        if: |
          steps.branch-info.outputs.can_delete == 'true' && 
          steps.security-check.outputs.is_safe == 'true' && 
          github.event.pull_request.merged == true
        uses: actions/github-script@v6
        with:
          script: |
            const branch = '${{ steps.branch-info.outputs.branch_name }}';
            const branchType = '${{ steps.branch-info.outputs.branch_type }}';
            const baseRef = '${{ github.base_ref }}';
            
            try {
              // Supprimer la branche
              await github.rest.git.deleteRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: `heads/${branch}`
              });
              
              // Ajouter un commentaire sur la PR
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: `✅ Branche \`${branch}\` supprimée automatiquement après fusion dans \`${baseRef}\`
                
                Type: ${branchType}
                Base: ${baseRef}
                
                Cette suppression a été effectuée car :
                - La Pull Request a été mergée avec succès
                - La branche source était de type ${branchType}/
                - La branche cible était ${baseRef}
                - Toutes les vérifications de sécurité ont été passées`
              });
            } catch (error) {
              console.error('Erreur lors de la suppression de la branche:', error);
              
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: `⚠️ Erreur lors de la suppression de la branche \`${branch}\`
                
                Erreur: ${error.message}
                
                Veuillez vérifier les logs de la pipeline ou supprimer la branche manuellement si nécessaire.`
              });
            }

      - name: Notifier en cas d'erreur de sécurité
        if: |
          steps.branch-info.outputs.can_delete == 'true' && 
          steps.security-check.outputs.is_safe == 'false' && 
          github.event.pull_request.merged == true
        uses: actions/github-script@v6
        with:
          script: |
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: `⚠️ La branche n'a pas été supprimée pour des raisons de sécurité.
              
              Branche: \`${{ steps.branch-info.outputs.branch_name }}\`
              Type: ${{ steps.branch-info.outputs.branch_type }}
              
              Veuillez vérifier que :
              1. La branche n'est pas une branche protégée
              2. Le format de la branche est correct (feature/ ou hotfix/)
              3. La branche cible est correcte (develop pour feature/, main pour hotfix/)`
            });
