name: Suppression Automatique des Branches

permissions:
  contents: write
  pull-requests: write
  issues: write

on:
  pull_request:
    types: [closed]
    branches:
      - develop
      - main

jobs:
  delete-merged-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Extraire les informations de la branche
        id: branch-info
        run: |
          HEAD_REF="${{ github.head_ref }}"
          BASE_REF="${{ github.base_ref }}"
          
          # Vérifier si c'est une branche feature vers develop ou hotfix vers main
          if [[ "$HEAD_REF" =~ ^feature/ && "$BASE_REF" == "develop" ]]; then
            echo "can_delete=true" >> $GITHUB_OUTPUT
            echo "branch_type=feature" >> $GITHUB_OUTPUT
          elif [[ "$HEAD_REF" =~ ^hotfix/ && "$BASE_REF" == "main" ]]; then
            echo "can_delete=true" >> $GITHUB_OUTPUT
            echo "branch_type=hotfix" >> $GITHUB_OUTPUT
          else
            echo "can_delete=false" >> $GITHUB_OUTPUT
            echo "branch_type=other" >> $GITHUB_OUTPUT
          fi
          
          echo "branch_name=$HEAD_REF" >> $GITHUB_OUTPUT

      - name: Vérifications de sécurité
        id: security-check
        if: steps.branch-info.outputs.can_delete == 'true' && github.event.pull_request.merged == true
        run: |
          # Liste de branches protégées
          PROTECTED_BRANCHES=("main" "develop" "master" "production" "staging")
          
          BRANCH="${{ steps.branch-info.outputs.branch_name }}"
          IS_SAFE=true
          
          # Vérifier si la branche est dans la liste des branches protégées
          for protected in "${PROTECTED_BRANCHES[@]}"; do
            if [[ "$BRANCH" == "$protected" ]]; then
              echo " ERREUR: Tentative de suppression d'une branche protégée ($BRANCH)"
              IS_SAFE=false
              break
            fi
          done
          
          # Vérifier le format de la branche
          if [[ ! "$BRANCH" =~ ^(feature|hotfix)/ ]]; then
            echo " ERREUR: Format de branche invalide ($BRANCH)"
            IS_SAFE=false
          fi
          
          if [[ "$IS_SAFE" == "true" ]]; then
            echo " Vérifications de sécurité réussies pour la branche $BRANCH"
          fi
          
          echo "is_safe=$IS_SAFE" >> $GITHUB_OUTPUT

      - name: Supprimer la branche
        if: |
          steps.branch-info.outputs.can_delete == 'true' && 
          steps.security-check.outputs.is_safe == 'true' && 
          github.event.pull_request.merged == true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          BRANCH="${{ steps.branch-info.outputs.branch_name }}"
          BRANCH_TYPE="${{ steps.branch-info.outputs.branch_type }}"
          
          # Supprimer la branche
          gh api \
            --method DELETE \
            /repos/${{ github.repository }}/git/refs/heads/$BRANCH
          
          echo " Branche $BRANCH supprimée avec succès"
          
          # Commenter sur l'issue associée
          if [[ "$BRANCH" =~ ^(feature|hotfix)/([0-9]+) ]]; then
            ISSUE_NUMBER="${BASH_REMATCH[2]}"
            
            EMOJI=""
            if [[ "$BRANCH_TYPE" == "hotfix" ]]; then
              EMOJI=""
            fi
            
            gh issue comment "$ISSUE_NUMBER" --body "$EMOJI La branche $BRANCH a été supprimée automatiquement après la fusion de la PR."
          fi

      - name: Notifier en cas d'erreur de sécurité
        if: |
          steps.branch-info.outputs.can_delete == 'true' && 
          steps.security-check.outputs.is_safe == 'false' && 
          github.event.pull_request.merged == true
        run: |
          echo " La branche n'a pas pu être supprimée en raison des vérifications de sécurité"
