name: Merge PR

on:
  pull_request:
    types: [closed]

jobs:
  check-merged:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Message de merge
        run: echo "La Pull Request a été mergée avec succès !"
